%macro contents(dsn,options);
%local dsn;
%let dsn=%upcase(&dsn);
%if &dsn=HELP %then %do;
	data _null_;
	file print;
	put	#3 @40 '**********HELP FOR THE %CONTENTS MACRO***********';
	put	#5 @40 '      Call as: %contents(library.dataset,options)        ';
	put	#7 @40 '           Ex %contents(rsipp12.w2_pp,varnum)           ';
	put	#9 @40 '*****************Thank you***********************';
	run;
	%return;
%end;
%if &dsn= %then %do;
	%put ERROR: Library.Dataset has been left NULL.;
	%put ERROR- Please provide LIB.DATASET;
	%put ERROR- -------------Thank you--------------;
	%return;
	%end;
%if not %sysfunc(exist(&dsn)) %then %do;
	%put ERROR: Data set &dsn does not exist.;
	%put ERROR- Macro will now terminate.;
	%return;
	%end;
proc contents data=&dsn &options;
run;
%mend contents;
